<a href="https://colab.research.google.com/github/lsantiago/PythonIntermedio/blob/master/Clases/Semana6_ALGEBRA/algebra_lineal_apuntes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Clase Nro. 6: Álgebra Lineal

> El álgebra lineal es una rama de las matemáticas que estudia conceptos tales como vectores, matrices, espacio dual, sistemas de ecuaciones lineales y en su enfoque de manera más formal, espacios vectoriales y sus transformaciones lineales

np.linalg: paquete de álgebra lineal en NumPy 

- Funciones básicas 
    - vectores
    - operaciones con vectores 
    - norma de un vector
    - operaciones con matrices
    - inversa de una matriz
    - determinante
- Resolución de sistemas


_Con el manejo básico de arrays en Python con NumPy, es hora de pasar a operaciones más interesantes como son las propias del Álgebra Lineal._

_Los productos escalares y las inversiones de matrices están por todas partes en los programas científicos e ingenieriles, así que vamos a estudiar cómo se realizan en Python._

Como sabemos, las operaciones del álgebra lineal aparecen con mucha frecuencia a la hora de resolver sistemas de ecuaciones en derivadas parciales y en general al linealizar problemas de todo tipo, y suele ser necesario resolver sistemas con un número enorme de ecuaciones e incógnitas. Gracias a los arrays de NumPy podemos abordar este tipo de cálculos en Python, ya que todas las funciones están escritas en C o Fortran y tenemos la opción de usar bibliotecas optimizadas al límite.

El paquete de álgebra lineal en NumPy se llama `linalg`, así que importando NumPy con la convención habitual podemos acceder a él escribiendo `np.linalg`. 

**Pero ¿Porqué álgebra lineal?** 

Si entendemos álgebra lineal podremos desarrollar una mejor intuición para el aprendizaje automático y algoritmos. Además, también seremos capaces de desarrollar algoritmos desde cero y hacer variaciones de ellos.

**¿Qué es un vector?**

Un vector tiene tanto magnitud como dirección. Utilizamos vectores para describir, por ejemplo, la velocidad de objetos en movimiento.

Por dirección, se refiere a dónde en el espacio apunta la “flecha”, y la magnitud te dice qué tan lejos debes ir en esa dirección. Si solo tienes magnitud, pero no dirección, entonces estás hablando de escalares. Una vez que le das al escalar alguna dirección, se convierte en un vector.

Un vector se representa con una letra minúscula y una flecha arriba, apuntando a la derecha

![vector](https://cdn-images-1.medium.com/max/800/1*6dAzelg6O36hbb74L7b1gQ.png)

In [1]:
import numpy as np

In [4]:
v = np.array([3, 2])
v

array([3, 2])

**Suma de vectores**

Para sumar los vectores (x₁,y₁) y (x₂,y₂), sumamos los componentes correspondientes de cada vector: (x₁+x₂,y₁+y₂)

![suma de vectores](https://cdn-images-1.medium.com/max/800/0*9r4Qmivh-MSPFqM3.png)

In [6]:
a = np.array([6, -2])
b = np.array([-4, 4])
a+b

array([2, 2])

**Multiplicar un vector por un escalar**

![](https://cdn-images-1.medium.com/max/800/0*YNlBN98aoAyV4DAL.png)

In [7]:
a = np.array([2, 1])
print(3 * a)

[6 3]


**Producto punto o escalar**

Esto suena raro, pero no es más que la multiplicación de vectores cuyo resultado es un escalar. Para calcular el producto escalar de dos vectores, primero debemos multiplicar los elementos correspondientes y luego sumar los términos del producto.

En la siguiente fórmula lo vemos mucho más fácil

![image.png](https://cdn-images-1.medium.com/max/800/0*lMEmcY_nXD4LOvHD.png)

<img src="https://cdn-images-1.medium.com/max/800/1*ys1bMjlrtchr_ClPah7Z2w.png" alt="drawing" width="500"/>

In [11]:
a = np.array([3, 2])
b = np.array([2, 2])
print(np.dot(a, b))
print(a.dot(b))

10
10


**Norma vectorial**

La norma es solo otro término para la magnitud de un vector y se denota con dos lineas dobles (||) en cada lado. Se define como una raíz cuadrada de la suma de cuadrados para cada componente de un vector

Pasos: 
- Elevar al cuadrado cada componente
- Suma todos los cuadrados
- Toma la raíz cuadrada

Trabajemos ahora con la formula:

![](https://cdn-images-1.medium.com/max/800/0*fIYtRzCI6vI8THet.png)

<img src="https://cdn-images-1.medium.com/max/800/1*95bAtiMefunHPhLbwOYnnQ.png" alt="drawing" width="500"/>

In [13]:
a = np.array([3, 2, 6])
print(np.linalg.norm(a))

7.0


**Vector unitario**

Los vectores unitarios son aquellos cuya magnitud es exactamente 1 unidad. Son muy útiles por diversas razones. Específicamente, los vectores unitarios [0,1] y [1,0] juntos pueden formar cualquier otro vector.

Un vector unitario se denota con mayor frecuencia con un símbolo de sombrero (^) y se determina calculando la norma y luego dividiendo cada componente del vector con la norma.

Suena complejo, pero vamos a hacer un ejercicio para poder ver que es más complejo de lo que imaginamos

![](https://cdn-images-1.medium.com/max/800/0*3Qkk3weTeyaMYthE.png)

<img src="https://cdn-images-1.medium.com/max/800/1*wFFS0a3soJRC7XlZxzJ6Kg.png" alt="drawing" width="400" height="400"/>

In [14]:
def unit_vector(a):
    return a/np.linalg.norm(a)

u = np.array([3, 6, 4])
print(unit_vector(u))

[0.38411064 0.76822128 0.51214752]


## Operaciones con matrices

 ¿Qué es una matriz? Una matriz es simplemente un arreglo rectangular de números
 
En data science las usamos un montón, así no nos demos cuenta. Es muy importante de diferenciar un vector de una matriz. En pocas palabras un vector es una sola columna (atributo) en su conjunto de datos y una matriz es una colección de todas las columnas

**Definición de matrices**

$A = \begin{equation}
\begin{bmatrix}
1 & 2 & 3\\
4 & 5 & 6\\
\end{bmatrix}
\end{equation}$

In [21]:
A = np.array([
    [1, 2, 3], 
    [4, 5, 6]])
print(A)

[[1 2 3]
 [4 5 6]]


$B = \begin{equation}
\begin{bmatrix}
5 & 5 & 5\\
5 & 5 & 5\\
\end{bmatrix}
\end{equation}$

In [23]:
B = np.full((2, 3), 5)
print(B)

[[5 5 5]
 [5 5 5]]


$v = \begin{equation}
\begin{bmatrix}
6\\
7\\
8
\end{bmatrix}
\end{equation}$

In [20]:
v = np.array([6, 7, 8])
print(v)

[6 7 8]


In [24]:
v.reshape(3, 1)

array([[6],
       [7],
       [8]])

**Suma de matrices**

In [32]:
#Generación de matriz con número aleatorios
M = np.random.rand(10).reshape(2, 5)
M

array([[0.16893808, 0.68055427, 0.68510975, 0.46087157, 0.96300747],
       [0.27432276, 0.13341453, 0.02883663, 0.34012649, 0.42683428]])

In [34]:
M[0][0]

0.1689380763904028

In [35]:
M[0, 0]

0.1689380763904028

In [36]:
M[0]

array([0.16893808, 0.68055427, 0.68510975, 0.46087157, 0.96300747])

In [37]:
M[1, 1:3]

array([0.13341453, 0.02883663])

In [38]:
M[1, -1]

0.42683428106255505

In [39]:
arreglo = np.arange(1, 11).reshape(2, 5)
arreglo

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [40]:
np.arange(0, 11, 3)

array([0, 3, 6, 9])

In [43]:
np.linspace(0, 20, 10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

In [45]:
np.logspace(0, 3, 100).reshape(10, 10)

array([[   1.        ,    1.07226722,    1.149757  ,    1.23284674,
           1.32194115,    1.41747416,    1.51991108,    1.62975083,
           1.7475284 ,    1.87381742],
       [   2.009233  ,    2.15443469,    2.3101297 ,    2.47707636,
           2.65608778,    2.84803587,    3.05385551,    3.27454916,
           3.51119173,    3.76493581],
       [   4.03701726,    4.32876128,    4.64158883,    4.97702356,
           5.33669923,    5.72236766,    6.13590727,    6.57933225,
           7.05480231,    7.56463328],
       [   8.11130831,    8.69749003,    9.32603347,   10.        ,
          10.72267222,   11.49756995,   12.32846739,   13.21941148,
          14.17474163,   15.19911083],
       [  16.29750835,   17.475284  ,   18.73817423,   20.09233003,
          21.5443469 ,   23.101297  ,   24.77076356,   26.56087783,
          28.48035868,   30.53855509],
       [  32.74549163,   35.11191734,   37.64935807,   40.37017259,
          43.28761281,   46.41588834,   49.77023564,   53

In [47]:
#np.logspace?

In [48]:
np.random.randint(1, 100, 20).reshape(5, 4)

array([[77, 24, 39, 44],
       [99, 13, 25, 88],
       [88, 94, 86, 25],
       [ 6, 50, 95, 36],
       [92,  4, 94,  4]])

![](https://cdn-images-1.medium.com/max/1600/0*eKgiNEikBO09MCN1.png)

In [49]:
print(A + B)

[[ 6  7  8]
 [ 9 10 11]]


**Resta de matrices**

In [50]:
print(A - B)

[[-4 -3 -2]
 [-1  0  1]]


**Multiplicación por un escalar**

![](https://cdn-images-1.medium.com/max/1600/0*RMuq3SZ_8Z4KE-48.png)

In [51]:
C = np.array([
    [3, 5],
    [1, 0]
])
C

array([[3, 5],
       [1, 0]])

In [52]:
print(2 * C)

[[ 6 10]
 [ 2  0]]


**Matriz transpuesta**

![](https://cdn-images-1.medium.com/max/1600/0*mrjFrMfmMcj4xsUe.png)

In [54]:
D = np.array([
    [3, 4],
    [1, 0]
])
print(D)

[[3 4]
 [1 0]]


In [55]:
print(D.T)

[[3 1]
 [4 0]]


**Matriz identidad**

In [57]:
I = np.identity(5)
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#help(np.linalg)

Recordemos que si queremos usar una función de un paquete pero no queremos escribir la "ruta" completa cada vez, podemos usar la sintaxis `from package import func`:

In [58]:
from numpy.linalg import norm, det
norm

<function numpy.linalg.norm(x, ord=None, axis=None, keepdims=False)>

El producto matricial usual (no el que se hace elemento a elemento, sino el del álgebra lineal) se calcula con la misma función que el producto matriz-vector y el producto escalar vector-vector: con la función `dot`, que **no** está en el paquete `linalg` sino directamente en `numpy` y no hace falta importarlo.

In [ ]:
np.dot

Una consideración importante a tener en cuenta es que en NumPy no hace falta ser estricto a la hora de manejar vectores como si fueran matrices columna, siempre que la operación sea consistente. Un vector es una matriz con una sola dimensión: por eso si calculamos su traspuesta no funciona.

In [59]:
M = np.array([
    [1, 2],
    [3, 4]
])
v = np.array([1, -1])

In [60]:
v

array([ 1, -1])

In [61]:
M.T

array([[1, 3],
       [2, 4]])

In [62]:
v.T

array([ 1, -1])

In [65]:
v.reshape(2,1)

array([[ 1],
       [-1]])

In [66]:
v.reshape(2,1).T

array([[ 1, -1]])

In [63]:
u = np.dot(M, v)
u

array([-1, -1])

**Multiplicación entre matrices**

In [74]:
A = np.array([
    [3, 2],
    [1, 3]
])
print(A.shape)

B = np.array([
    [2, 2],
    [1, 2]
])
print(B.shape)

(2, 2)
(2, 2)


In [72]:
# producto matricial
np.dot(A, B)

array([[ 8, 10],
       [ 5,  8]])

In [77]:
A = np.array([
    [5, 3, -4, -2],
    [8, -1, 0, -3]
]).reshape(2, 4)
print(A)
B = np.array([
    [1, 4, 0],
    [-5, 3, 7],
    [0, -9, 5],
    [5, 1, 4]
]).reshape(4, 3)
print(B)


[[ 5  3 -4 -2]
 [ 8 -1  0 -3]]
[[ 1  4  0]
 [-5  3  7]
 [ 0 -9  5]
 [ 5  1  4]]


(2, 4)


In [76]:
print(np.dot(A, B))

[[-20  63  -7]
 [ -2  26 -19]]



**Determinante de una matriz**

In [78]:
# calcula el determinante de una matriz
A = np.array([
    [3, 2],
    [1, 3]
])

In [79]:
np.linalg.det(A)

7.000000000000001

**Inversa de una matriz**

Para calcular la matriz inversa en Python, use la función linalg.inv () del módulo numpy.

linalg.inv(x) 

El parámetro x de la función es una matriz cuadrada invertible M definida con la función array() de numpy. 

La función genera la matriz inversa M-1 de la matriz M.

> ¿Qué es la matriz inversa? La matriz inversa M-1 de una matriz cuadrada es una matriz tal que el producto M · M-1 es igual a una matriz de identidad I.



<img src="http://how.okpedia.org/data/okpediaorg/matrix-inverse-identity-formula.gif" alt="drawing" />


Encuentre la matriz inversa M-1 de la siguiente matriz invertible M.

![](http://how.okpedia.org/data/okpediaorg/matrix-inverse-example-python-1.gif)

In [90]:
m = np.array([
    [3,4,-1],
    [2,0,1],
    [1,3,-2]])
m

array([[ 3,  4, -1],
       [ 2,  0,  1],
       [ 1,  3, -2]])

In [91]:
# Calcula la matriz inversa con la función linalg.inv().
Minv = np.linalg.inv(m)
print(Minv)

[[-0.6  1.   0.8]
 [ 1.  -1.  -1. ]
 [ 1.2 -1.  -1.6]]


La matriz de salida inversa es también un objeto array(). Se puede leer como una lista anidada. Los elementos de la matriz inversa son números reales.

![](http://how.okpedia.org/data/okpediaorg/matrix-inverse-example-9.gif)

Verificación. El producto de la matriz M para la matriz M-1 es una matriz de identidad.


![](http://how.okpedia.org/data/okpediaorg/matrix-inverse-example-10.gif)

In [94]:
# verificación
Mident = np.dot(m, Minv)
print(np.round(Mident))

[[ 1. -0. -0.]
 [ 0.  1. -0.]
 [ 0. -0.  1.]]


**Otro ejemplo** 
Encontrar el determinante y la matriz inversa de D.

$ D = \begin{equation}
\begin{bmatrix}
1 & 2\\
3 & 4\\
\end{bmatrix}
\end{equation}$


In [99]:
D = np.array([
    [1, 2], 
    [3, 4]
    ])
D

array([[1, 2],
       [3, 4]])

In [100]:
# cálculo del determinante
detD = np.linalg.det(D)
print(detD)

-2.0000000000000004


In [101]:
# y el inverso
invD = np.linalg.inv(D)
print(invD)

[[-2.   1. ]
 [ 1.5 -0.5]]


**Solución de ecuaciones con matrices**

1. Resolver el siguiente sistema de ecuaciones

$\begin{eqnarray}
3x + y  = 9 \\
x + 2y = 8 \\
\end{eqnarray}$

In [103]:
coef = np.array([
    [3, 1],
    [1, 2]
])

result = np.array([9, 8])

sol = np.linalg.solve(coef, result)

In [104]:
print(sol)

[2. 3.]


2. Al resolver un problema de circuito eléctrico, uno se encuentra rápidamente empantanado en
una gran cantidad de ecuaciones simultáneas. Por ejemplo, considere el circuito eléctrico que se
muestra en la figura 9.5. Contiene una sola fuente de voltaje y cinco reóstatos. Puede analizar este
circuito al dividirlo en partes más pequeñas y usar dos hechos básicos en torno a la electricidad

Sumatoria de voltaje alrededor de un circuito debe ser cero
Voltaje = corriente x resistencia (V = iR)

Seguir el lazo inferior izquierdo resulta en la primera ecuación:

$-V_1 +R_2(i_1-i_2)+R_4(i_1-i_3)=0$

Seguir el lazo superior resulta en la segunda ecuación:

$R_1i_2+R_3(i_2-i_3)+R_2(i_2-i_1)=0$

Finalmente, seguir el lazo inferior derecho resulta en la última ecuación:

$R_3(i_3-i_2)+R_5i_3+R_4(i_3-i_1)=0$

Dado que se conocen todas las resistencias (los valores R) y el voltaje, se tienen tres ecuaciones y tres incógnitas. Ahora se necesita reordenar las ecuaciones de modo que estén en una forma en la que se pueda aplicar una solución matricial. En otras palabras, se necesita aislar las íes del modo siguiente:

![](./img/resistencias.png)

Cree un programa en python para resolver estas ecuaciones con el método de matriz inversa y empleando el método solve de linalg

![](./img/Figura9.5.png)

In [109]:
import numpy as np

R = [float(sR) for sR in input("Ingrese 5 resistencias: ").split()]
V = float(input("Ingrese el valor del voltaje: "))

R1 = R[0]
R2 = R[1]
R3 = R[2]
R4 = R[3]
R5 = R[4]

coef = np.array([
    [(R2 + R4), -R2, -R4],
    [-R2, (R1 + R2 + R3), -R3],
    [-R4, -R3, (R3 + R4 + R5)]
])

result = np.array([V, 0, 0])
#Primer método
I = np.linalg.solve(coef, result)
print(I)

#Segundo método
I = np.dot(np.linalg.inv(coef), result)
print(I)

[1.69354839 0.96774194 0.80645161]
[1.69354839 0.96774194 0.80645161]


#### Lectura de una Matriz

In [110]:
NUM_ROWS = 4
a = [[int(j) for j in input().split()] for i in range(NUM_ROWS)]
a

[[1, 2, 3, 4], [4, 5, 6, 7], [8, 9, 10, 11], [12, 13, 14, 15]]

### Ejercicios

1- Hallar el producto de estas dos matrices y su determinante:

$$\begin{pmatrix} 1 & 0 & 0 \\ 2 & 1 & 1 \\ -1 & 0 & 1 \end{pmatrix} \begin{pmatrix} 2 & 3 & -1 \\ 0 & -2 & 1 \\ 0 & 0 & 3 \end{pmatrix}$$

In [113]:
from numpy.linalg import det

In [114]:
a = np.array([
    [1, 0, 0],
    [2, 1, 1],
    [-1, 0, 1]
])
print(a)

[[ 1  0  0]
 [ 2  1  1]
 [-1  0  1]]


In [115]:
b = np.array([
    [2, 3, -1],
    [0, -2, 1],
    [0, 0, 3]
])

In [117]:
producto = np.dot(a, b)
print(det(producto))

-12.0


3- Resuelva el siguiente sistema de ecuaciones

$\begin{eqnarray}
x + 2y  = 3 \\
3x + 4y = 5 \\
\end{eqnarray}$

In [118]:
coef = np.array([
    [1, 2],
    [3, 4]
])

res = np.array([3 , 5])

print(np.linalg.solve(coef, res))

[-1.  2.]


4- Un ingeniereo escribe dos ecuaciones que describen el circuito, como sigue: 

$\begin{gather}
300I_{1} + 500(I_{1}-I_{2})-20 = 0\\
200I_{2} + 500(I_{2}-I_{1}) +10 = 0\\
\end{gather}$

![circuito](https://github.com/lsantiago/PythonIntermedio/blob/master/Clases/Semana6_ALGEBRA/img/problem4.png?raw=1)

Coloque las dos ecuaciones en forma estándar y resuelva las dos ecuaciones:

In [119]:
coef = np.array([
    [800, -500],
    [-500, 700]
])

res = np.array([20, -10])

print(np.linalg.solve(coef, res))

[0.02903226 0.00645161]


5- Resolver el siguiente sistema de ecuaciones

![](https://github.com/lsantiago/PythonIntermedio/blob/master/Clases/Semana6_ALGEBRA/img/problem5.png?raw=1)

In [122]:
coef = np.array([
    [6000, -2000, -4000],
    [-2000, 15000, -5000],
    [4000, -5000, 12000]
])

res = np.array([10, 0, 0])

solve = np.linalg.solve(coef, res)
print(solve)

[0.00275801 0.00078292 0.00124555]


3- Resolver el siguiente sistema:

$$ \begin{pmatrix} 2 & 0 & 0 \\ -1 & 1 & 0 \\ 3 & 2 & -1 \end{pmatrix} \begin{pmatrix} 1 & 1 & 1 \\ 0 & 1 & 2 \\ 0 & 0 & 1 \end{pmatrix} \begin{pmatrix} x \\ y \\ z \end{pmatrix} = \begin{pmatrix} -1 \\ 3 \\ 0 \end{pmatrix} $$

In [129]:
m = np.array([
    [2, 0, 0],
    [-1, 1, 0],
    [3, 2, -1]
])
print(m)

[[ 2  0  0]
 [-1  1  0]
 [ 3  2 -1]]


In [128]:
m1 = np.array([
    [1, 1, 1],
    [0, 1, 2],
    [0, 0, 1]
])
print(m1)

[[1 1 1]
 [0 1 2]
 [0 0 1]]


In [ ]:
res = np.array([-1, 3, 0])

In [131]:
print(np.linalg.solve(np.dot(m, m1), res))

[ 25. -45.  25.]
